services:
  footsies-server:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - footsies-dojo-net

networks:
  footsies-dojo-net:
    name: footsies-dojo-net
