import { AttackData } from "./types";

export const ATTACKS: Record<string, AttackData> = {
  light: {
    type: "light",
    startup: 4,
    active: 3,
    recovery: 8,
    damage: 60,
    chipDamage: 5,
    hitstun: 12,
    blockstun: 10,
    range: 55,
    pushback: 8,
    guardPushback: 2,
    attackerGuardPushback: 3,
  },
  medium: {
    type: "medium",
    startup: 8,
    active: 4,
    recovery: 14,
    damage: 100,
    chipDamage: 10,
    hitstun: 18,
    blockstun: 14,
    range: 80,
    pushback: 14,
    guardPushback: 3,
    attackerGuardPushback: 4,
  },
  heavy: {
    type: "heavy",
    startup: 20,
    active: 5,
    recovery: 22,
    damage: 160,
    chipDamage: 15,
    hitstun: 24,
    blockstun: 18,
    range: 110,
    pushback: 22,
    guardPushback: 4,
    attackerGuardPushback: 5,
  },
};
